#!/usr/bin/ruby
require 'erb'
require_relative 'movie'

movie = Movie.new(title: 'Mom Attacks', director: 'George', year: '1600')
movie2 = Movie.new(title: 'Godzilla', director: 'Eddie', year: '1999')
movies = [movie,movie2]

template = File.read('example.html.erb')

b = binding
# puts ERB.new(template).result(movie.instance_eval { binding })
puts ERB.new(template).result(b)

